- package-lock.json
- package.json
- views/index.ejs
i have added the follow us section
> Added follow-us section

- README.md
Fix issue #7 , update the readme file, where I added some animations (icons), change the alignment of text and few more changes and also add contribution section.
> Add some style and contribution section in docs

- .github/workflows/greetings.yml
Fixed #27 
**Description:**
This pull request implements a new GitHub Actions workflow named "Greetings," which automatically greets users who open new issues or pull requests in this repository.
**Key Features:**
- **Automatic Greeting**: Users will receive an immediate acknowledgment when they create an issue or pull request. The messages are:
- **For Issues**: "👋 Thank you for raising an issue! We appreciate your effort in helping us improve. Our team will review it shortly. Stay tuned!"
- **For Pull Requests**: "🎉 Thank you for your contribution! Your pull request has been submitted successfully. A maintainer will review it as soon as possible. We appreciate your support in making this project better."
**Implementation Details:**
- Created a workflow file named `greetings.yml` in the …
> Fixed #27 : Automated Greeting Workflow

- views/partials/searchbar.ejs
fixes #13 
before
https://github.com/user-attachments/assets/01f74a85-13d4-42b6-b7cb-f1845796ddf1
after
https://github.com/user-attachments/assets/f6a9a74b-60bc-428b-a726-7122d43da998
is this okay?
> fixes the search bar

- views/index.ejs
With functionality like follow subscribe etc
This is just one screenshot more functionality are there
> Added the footer section

- views/index.ejs
issue no #33 
twitter logo chaned to x
> twitter logo change in to x

- views/partials/navbar.ejs
fixes #37 
https://github.com/user-attachments/assets/218d1d53-4092-4b1e-a887-e4e96a910aae
> Added hover effect to nav items

- views/display.ejs
the preview of card ui has been sent , review the changes and accept the pull request
> changed card ui

- package-lock.json
- views/auth.ejs
Enhanced the ui/ux of the button of signup signin forms
issue no :- #57 
Before :- 
After :- 
Assign this to me and put relevent labels of gssoc 2024 ext, hacktoberfest, level 1 with space, not accepted without space and don't include - in it okay.
> Enhanced the ui/ux of the button of signup signin forms

- public/formstyle.css
> Increased the sign-in button height and changed the border radius

- README.md
I believe these updates could enhance user understanding and engagement with the project.
> Enhancing Readme.md

- views/index.ejs
I have completed the footer and made it modern and sleek...
make sure to add the labels...
thanks:)
> footer-updated

- public/formstyle.css
Reverts swarooppatilx/scruter#60
> Revert "enhanced ui"

- views/index.ejs
> Designed and added hover animation to information section

- SECURITY.md
This PR introduces a new `security.md` file, which defines Scruter's security policy. The goal of this document is to provide clear guidelines for reporting vulnerabilities and to outline the scope of our security support. Key features include:
- **Vulnerability Reporting Process:** Instructions for security researchers on how to report vulnerabilities responsibly, including email contact and steps to follow.
- **Supported Versions:** A table that lists the versions of Scruter that are currently supported with security updates. Users are encouraged to use the latest version to ensure they receive the most up-to-date patches.
- **Expectations for Reporters:** Guidelines for responsible disclosure, including details on what constitutes a valid report and what actions should be avoided …
> feat: add security policy and supported versions to security.md

- uploads/index.html
- views/auth.ejs
Hello PR,
Fixed issue number - #110 
Issue-
Issue Fixed -
> Fixed Login page UI is messed up issue ! #110

- PULL_REQUEST_TEMPLATE.md
Created a structured and professional GitHub Pull Request (PR) template to streamline the contribution process. The template includes sections for describing changes, listing tech stack and dependencies, attaching relevant screenshots, and following project guidelines. This ensures clarity and consistency in PR submissions, helping maintain high code quality and efficient review processes.
Fixes #138 
> Adding a PR/MR Template 

- views/partials/footer.ejs
> link hower effect added

- views/auth.ejs
- views/index.ejs
In this PR, i have fixed the issues in login and signup page, also i have added a scroll to top button to the website
Fixes #88 and #89 
https://github.com/user-attachments/assets/7b0f4dd2-db5f-4912-a731-f1dc74a8d3ef
-
> Fixed login, signup page and added scroll to top button

- package-lock.json
- package.json
- views/partials/bottom_nav.ejs
- views/partials/navbar.ejs
This PR adds a "Sign-Up" button on the home page, which directs users to the sign-up page. This feature aims to enhance user accessibility by providing a direct route for new users to register.
Fixes #81 
Before:
After:
- Navigate to the home page.
- Verify that the "Sign-Up" button is visible and functional.
- Click on the "Sign-Up" button to ensure it redirects to the sign-up page.
> add sign-up(register) button

- views/partials/footer.ejs
I have updated the hover effect for the .quick-link and .help-desk classes, replacing the previous version with an enhanced one. The new CSS adds a smoother scaling effect and underline when the elements are hovered over. This change improves user interaction by smoothly increasing the size of the elements to 110% while underlining them, making the interface more dynamic and visually appealing. The added transition ensures that the scaling effect is applied seamlessly, creating a better overall user experience.
> added a hover effect on both help desk and quick link section

- views/index.ejs
I have added scroll progress bar successfully
https://github.com/user-attachments/assets/b8d8806b-0ebe-47fb-b728-4782e2edecdb
> added scroll progress

- app.js
- views/auth.ejs
- views/contributors.ejs
- views/dashboard.ejs
- views/partials/navbar.ejs
Based on #134, it creates a Dashboard Page, that displays the Username, UserID, and Phone Number of the user.
It also has the options for changing the Username, Password, etc.
Please refer to the following video @swarooppatilx and let me know if everything is alright. Thank you!
Fixes #134 
https://github.com/user-attachments/assets/b195275e-cb67-4e59-9a07-1b0699162401
Created new users that have phone numbers and worked on them. The data displayed perfectly as shown in the video.
> Work on feature#134

- app.js
- uploads/aboutus.html
- views/about.ejs
I have added `About Us ` Page , which contains sections - **About Us** , **Our Mission** , **What we Offer** , **How It Works** , **Our Values** 
Fixes #139 
Before Fix:
After Fix:
To test the change:
Check the Separate File: Open the aboutus.html file locally in a browser and verify that the page displays correctly. Ensure that all the content and styling work as expected.
Link Test: Add a temporary link to the main index.html file that points to the aboutus.html file. For example, add a <a href="aboutus.html">About Us</a> link in …
> About Us Page Added

- app.js
- views/privacy-policy.ejs
- views/terms.ejs
I have created pages for both terms and conditions and privacy-policy successfully.
Could you please consider it as level 2, 
https://github.com/user-attachments/assets/14f157b7-6c90-4936-bfdb-03522b0167bb
> added terms and privacy content

- views/partials/navbar.ejs
https://www.awesomescreenshot.com/video/32499364?key=246c37da202d8e27ddc1b433a1509573
Fixes #142
> modified the nav layout

- public/css/global.css
issue #200
fix dark mode issue (footer not visible )
Fixes #(issue)
https://github.com/user-attachments/assets/d2f2bd59-d121-45e8-bfe7-effc11cb3d1d
> fix dark mode

- public/css/global.css
> Fixed footer dark mode issue

- views/partials/navbar.ejs
> header dark mode visibility fixed

- views/partials/navbar.ejs
Fixed issue number - #125 #154 #191
> Issue Fixed 

- .env.example
- package-lock.json
- package.json
- public/css/formstyle.css
- public/css/global.css
- views/auth.ejs
Fixed Dark mode issue on sign up page and authentication error issue
Fixes #180 
https://github.com/user-attachments/assets/1b155961-9850-442e-9dc4-32d91de6e216
✅ Bug fix (non-breaking change which fixes an issue)
User can go to login/signup page and see that the CSS works well!
> Fixed Dark mode issue on sign up page and authentication error issue

- views/about.ejs
- **Navbar Sticky**: Implemented a sticky navigation bar for improved user experience.
- **Responsive Design**: Enhanced responsiveness for various screen sizes, ensuring a better layout on mobile devices.
- **About Us Section**:
- Added mission and values cards for clarity and engagement.
- Included a flexible layout for the "What We Offer" and "Our Values" sections using flexbox for better alignment.
- **Styling Improvements**:
- Updated color schemes for buttons and list items for better aesthetics.
- Enhanced hover effects for cards and buttons to improve user interaction.
- **Dynamic Title**: Incorporated a dynamic title using EJS to reflect the page context.
Kindly merge it. @swarooppatilx 
If any changes are needed, do let me know!!
fixes: #197 
I would like to request a Level 3 …
> About Us Page Updated

- views/terms.ejs
This pull request includes significant updates to the Terms and Conditions page, enhancing its design and responsiveness. The following changes have been made:
- **Responsive Design**: Added media queries to ensure the layout adapts well to various screen sizes (768px and 480px).
- **Card Style**: Implemented a card-style layout for terms, improving readability and aesthetics.
- **Hover Effects**: Added hover effects on cards to enhance user interaction.
- **Button Adjustments**: Made the "Back to Home" button full width on smaller screens for better usability.
- **Text Alignment**: Center-aligned the main heading for improved appearance on smaller devices.
Kindly merge it.
fixes: #195 @swarooppatilx 
I would like to request a Level 3 assignment for this pull request. The changes made …
> Update Terms and Conditions Page

- public/js/client-validation.js
This PR simplifies the form validation logic for the item submission form by centralizing validation and reducing redundancy. It improves code readability and maintainability, making future updates easier. No specific issues are fixed with this change, but it enhances the overall user experience by ensuring more reliable form submissions.
To verify the changes, please follow these steps:
1. Navigate to the item submission form.
2. Fill in the form with various valid and invalid inputs.
3. Ensure that appropriate error messages are displayed for invalid fields.
4. Confirm that valid submissions are processed correctly without any errors.
> refactor: simplify form validation logic

- views/auth.ejs
> Fix Scrolling Functionality on Signup Page

- views/auth.ejs
> added remember me interface

- package-lock.json
- package.json
- public/js/gsap.js
- views/index.ejs
- views/partials/navbar.ejs
- views/partials/searchbar.ejs
This Pr will add some Gsap animations to landing page which are visible in demo video below
Fixes #196 
https://github.com/user-attachments/assets/183e1a6b-ba1b-417a-ada2-73d900aa3e0f
Load website the animations will be visible
> added gsap animations

- app.js
- views/faq.ejs
I have added faq page
https://github.com/user-attachments/assets/42da710d-2f7c-4869-821f-c67305bdb905
> added faq page

- views/privacy-policy.ejs
This pull request introduces significant enhancements to the user interface of the Privacy Policy page. The main features include:
- ### **Dark and Light Theme Toggle:** Users can now switch between dark and light themes, improving readability and user experience based on their preferences.
- **Improved UI Design:** The overall design has been refined with better color contrast, card hover effects, and responsive design adjustments for mobile devices.
- **Welcome Message Visibility:** Adjustments were made to ensure the welcome message is clearly visible in both light and dark themes.
- **Card Hover Effects:** Cards now have a hover effect for better interactivity and user engagement.
- **Button Styling:** Enhanced button styles for better visibility and user interaction.
I believe these …
> UI Improvements and Theme Toggle Feature on Privacy Policy page

- app.js
- views/partials/footer.ejs
- views/terms-page.ejs
I have added terms and conditions page
https://github.com/user-attachments/assets/a0ff911b-6fc7-4b78-be49-2ec17b2bd669
> added terms and conditions

- views/index.ejs
- views/partials/head.ejs
I have enhanced the default scroll bar
https://github.com/user-attachments/assets/96c51e24-8dea-4366-959e-f39981e53689
> enhanced default scroll bar

- app.js
- views/help.ejs
added a Help Center page for which link is given in the footer. Its appearance works in both light and dark mode.
Fixes #281 
Before:
After:
> added help center page

- app.js
- views/support.ejs
added a Support page for which link is given in the footer. Its appearance works in both light and dark mode.
Fixes #292 
Before:
After:
> Adding a Support Page

- app.js
- views/display.ejs
- views/edit.ejs
- views/form.ejs
- Added edit page section for house, markets and food
- Used same format as form
- Fixes #49 
https://github.com/user-attachments/assets/22f5b18f-6948-4804-bdb8-208e81f01cbc
> Implemented Edit Post Feature

- views/contributors.ejs
added back to top button please check it
added scroll to top button  as on issue number #68 
Fixes #(issue)
https://github.com/user-attachments/assets/3c285fd0-ec7b-415d-9895-2ec2349abb46
> Update contributors.ejs added scroll to top button 

- .env.example
- public/css/global.css
- views/index.ejs
- views/partials/footer.ejs
- views/privacy-policy.ejs
Social Media Icons Size is too large in terms and condition page in footer. I resolve this Issues by decreaseing the size and additonal i changes some css because some make changes so social media icons not view properly.
When Hovering Underline appears  but now no underline when hovering.
Text is not Visible on button when dark mode is enabled. Now No visibility issue.
Social Media icons not Centered. Now all icons centered.
Fixes #303 
https://github.com/user-attachments/assets/1e7bdea1-8997-4dc2-8adf-93128af56919
> Fixes the Issues raised in PR

- scruter-nextjs/app/(routes)/page.tsx
- scruter-nextjs/components/ui/CustomCursor.jsx
- scruter-nextjs/package-lock.json
- scruter-nextjs/package.json
I have added animated cursor to enhance the UI of the webpage.
Fixes #283 
https://github.com/user-attachments/assets/2ef348c3-9118-4ac2-9e11-86c51a229dad
No need of test
> animated curser added

- app.js
- views/partials/searchbar.ejs
I have added sortByPrice Functionality in the Housing Page.
Fixes #318 
https://github.com/user-attachments/assets/1b71f4ea-a8ae-47a8-a9bc-90a132181e7a
> Added Sort By Price Functionality | Issue #318

- app.js
I have added sortByPrice Functionality in the Market Page.
Fixes #321 
https://github.com/user-attachments/assets/83d92872-6760-433c-8a54-8e0c796de559
> Added Sort By Price Functionality in Market | Issue #321

- app.js
- database.js
I have added sortByPrice Functionality in the Food Page.
Fixes #320 
https://github.com/user-attachments/assets/2132fe9b-34a4-48ca-adcf-62334695edb5
> Added Sort By Price Functionality in Food Page | Issue #320

- views/display.ejs
- views/index.ejs
I have added the BackToTop button on all the pages.
Fixes #319 
https://github.com/user-attachments/assets/58f9ba10-8eea-43b1-8a4d-d8c4fe75f96e
> Added BackToTop Button in All the Page | Issue #319

- .github/ISSUE_TEMPLATE/Documentation.yml
This PR updates the project documentation, specifically enhancing the sections on environment setup, API usage, and contribution guidelines. The update addresses missing details on environment configuration, common troubleshooting steps, and provides updated API examples and contribution instructions. 
**Issue Fixed**: Fixes #341 
This change improves the user experience by making setup and usage clearer and simplifying the onboarding process for new contributors. It also ensures that documentation aligns with the latest workflows and code style guidelines.
---
---
1. **Environment Setup Test**:  
- Follow the updated setup instructions on a fresh environment to ensure accuracy and completeness.
2. **API Usage Test**:  
- Verify the new API instructions by testing each endpoint example …
> CREATE DOCUMENTATION TEMPLATE

- .github/ISSUE_TEMPLATE/custom.yml
This PR introduces a custom issue template for the project, designed to enhance the process of issue reporting and tracking. Here’s why the template is necessary and the key components included:
**Why a Custom Issue Template is Necessary:**
- **Consistency**: Ensures a uniform structure for all reported issues, making it easier for contributors and maintainers to review and prioritize.
- **Clarity**: Helps users articulate issues clearly, providing all essential information up front, reducing the need for follow-up questions.
- **Efficiency**: Guides users through the reporting process, saving time on reviewing issues and streamlining workflows for both reporters and maintainers.
- **Prioritization**: Based on the information in the template, this section assists in assessing the severity …
> CREATE A CUSTOM ISSUE TEMPLATE

- views/terms-page.ejs
I have completely redesign the Terms and Conditions Page and made a Modern Styled Page.
Fixes #323 
https://github.com/user-attachments/assets/9d6c6bea-acc3-418d-ae0e-3f7fd43e72d7
> Completely Redesign the T&C Page | Issue #323

- .github/ISSUE_TEMPLATE/custom.yml
- README.md
The issue relates to the absence of an enhanced footer in the README file, specifically the missing social media links that would allow contributors and users to easily connect with the project team or follow updates. A footer with social media links can increase community engagement by making it easier for users to follow the project’s progress, connect on professional platforms, and share resources. This PR adds an enhanced footer with social media links.
Fixes #353 
1. **Verify the README**: Check the footer section of the README file to ensure the social media links are correctly displayed and clickable.
2. **Click on Links**: Test each social media link to confirm that they redirect to the correct profiles.
3. **Visual Check**: Ensure that the icons and layout of the footer look …
> Enhanced Footer with Social Links

- views/index.ejs
I have enhanced the scroll to top feature, added animation to it, and previously it scrolling to top too slow, i enhanced the scroll speed
https://github.com/user-attachments/assets/f4f59181-3acf-49f1-9300-1ed40dd84415
issue no : #376 
Fixes #(issue)
> enhanced scroll to top

- app.js
- views/contact.ejs
- views/partials/footer.ejs
I have added the content to contact us page and made it align with the website styling
issue no : #291 
https://github.com/user-attachments/assets/979c1945-c07b-444d-83f6-80cc867b18f9
Fixes #(issue)
> added content to contact us page

- views/help.ejs
- views/privacy-policy.ejs
- views/support.ejs
I have made privacy policy, support page and help center to look similar like Terms of Use page
issue no : #387 
https://github.com/user-attachments/assets/81e8220d-971e-4c50-b761-f63d58bf0bad
Fixes #(issue)
> enhanced privacy policy, help center, support pages

- views/faq.ejs
I have enhanced the faq page too
From this
https://github.com/user-attachments/assets/f676ff67-3b45-40f5-943d-6f61e53b6eab
to this
https://github.com/user-attachments/assets/aa4e31c7-24ca-477d-b4e7-d692da7025f0
issue no : #388 
Fixes #(issue)
> enhanced faq page like terms page

- views/index.ejs
- views/partials/testimonial.ejs
This pull request introduces a new carousel component for displaying customer reviews on the platform. The carousel enhances the user experience by allowing users to easily browse through multiple reviews without leaving the current view.
- **Created `Testimonial` Component**: This component handles the rendering of review items in a carousel format.
- **Styled the Carousel**: Applied responsive styles using Bootstrap CSS to ensure the carousel looks great on all devices.
- **Implemented Navigation Controls**: Added previous and next buttons for navigating through reviews.
- **Added Auto-Slide Feature**: The carousel automatically transitions between reviews every few seconds.
-  Closes #377 
- Chore (refactoring code, technical debt, …
> [FEAT] Added Testimonial Carousel on Homepage with AutoScroll

- views/partials/searchbar.ejs
Hello I have added the dynamic search feature in housing route
The houses are dynamically filtered based on title when user starts typing in search box
Fixes #398 
> dynamic search added

- app.js
Reverts swarooppatilx/scruter#411
> Revert "Fix code scanning alert no. 49: Uncontrolled data used in path expression"

- package-lock.json
Reverts swarooppatilx/scruter#434
> Revert "chore: bump @types/whatwg-url from 11.0.4 to 11.0.5"

- views/edit.ejs
- views/form.ejs
I have added the food price field in the form 
Fixes #423
> add food price field in form

- public/css/global.css
- views/auth.ejs
I have fixed the UI overlapping issue in the signup form pls check it
Fixes #479
> Fixed ui issue

- README.md
Updated readme to fix contributing file link
Fixes #504 
> Updated Readme.md to fix the contributing file link

- scruter-nextjs/actions/user/userDELETE.tsx
- scruter-nextjs/actions/user/userEDIT.tsx
- scruter-nextjs/app/api/testing/user/[userId]/route.ts
- scruter-nextjs/app/api/testing/user/route.ts
CRUD actions for user and API to test them
https://github.com/user-attachments/assets/fb99146c-c33a-4a9b-bd45-9d81205e23c4
https://github.com/user-attachments/assets/4d7d54e1-7f13-47ad-b284-b81b672fbb8e
closes #496
> CRUD actions for user and API to test them

- scruter-nextjs/actions/user/bookmarks/CREATE_bookmark.ts
- scruter-nextjs/actions/user/bookmarks/DELETE_bookmark.ts
- scruter-nextjs/actions/user/bookmarks/EXISTS_bookmark.ts
- scruter-nextjs/actions/user/bookmarks/GETBYUSER_bookmark.ts
- scruter-nextjs/app/api/testing/bookmark/[userId]/[listingId]/route.ts
- scruter-nextjs/app/api/testing/bookmark/[userId]/route.ts
- scruter-nextjs/prisma/schema.prisma
This pull request introduces the backend infrastructure for managing bookmarks within the application. It adds schema definitions, server actions, and API endpoints necessary to support bookmarking functionality for users, allowing them to save listings.
1. **Database Schema**:
- Added a `Bookmark` model to create a many-to-many relationship between `User` and `Listing`.
- Defined relations to enable seamless querying and management of bookmarks in the Prisma schema.
- Updated the schema with referential integrity constraints and default values where applicable.
2. **Server Actions**:
- Created CRUD server actions in the `actions/user` folder to handle bookmarking operations.
- Implemented the following actions:
- **Add Bookmark**: Allows users to bookmark listings.
- **Remove Bookmark**: …
> Bookmark backend: schema, serveractions and testing API

- public/css/infopage.css
- views/dashboard.ejs
I have fixed the dark mode visibility issue in profile page and also changed the UI
Pls check it
Fixes #505
> Change profile page ui

- views/display.ejs
[Feat] Buy Now to WhatsApp chat #424 
Fixes #424 
>  [Feat] Buy Now to WhatsApp chat #424 

- scruter-nextjs/app/admin/[adminId]/page.tsx
- scruter-nextjs/app/admin/auth/components/login-form.tsx
- scruter-nextjs/app/admin/auth/page.tsx
- scruter-nextjs/lib/auth.ts
- scruter-nextjs/prisma/schema.prisma
- scruter-nextjs/types/next-auth.d.ts
This PR introduces the **Admin Role** for the application, adds functionality for **Admin Login**, and modifies the authentication logic to handle the `admin` role type. The following changes have been made:
1. **Admin Schema in Prisma**:
- A new **Admin** model has been added to the Prisma schema.
- The Admin model includes:
- `id`: Unique identifier.
- `email`: Admin email for login.
- `password`: Admin's encrypted password.
- `role`: Admin role, which could be used for different permissions.
2. **NextAuth Role Configuration**:
- Modified the NextAuth configuration to include an `admin` role type.
- The `role` of the user is now part of the JWT token and is checked during session creation.
- Admins are given special access based on their `role`.
3. **LoginPage**:
- Created the admin …
> Admin: schema , admin Role Type-in nextauth  , loginPage , auth.ts modification

- scruter-nextjs/actions/seller/listing.tsx
- scruter-nextjs/components/Maps/PinDropInput/LazyMapWithPin.tsx
- scruter-nextjs/components/Maps/PinDropInput/mapWithPin.tsx
- scruter-nextjs/components/Maps/PinDropInput/mapWithPinComp.tsx
- scruter-nextjs/package-lock.json
- scruter-nextjs/package.json
- scruter-nextjs/prisma/schema.prisma
> Add mapWithPinDrop input component and it's lazy loader component and modify schema and serveractions to accomodate location functionality

- scruter-nextjs/components/common/footer.tsx
[Feat] Fully revamping the footer section with addtional functionalities #503 
Fixes #203 
implementated dark mode, made responsiveness.
if any additonal changes required kindly let me know.
>  [Feat] Fully revamping the footer section with addtional functionalities #503 

- views/partials/footer.ejs
- views/team.ejs
[Feat] improving UI design of team page #417 
Fixes #417 
>  [Feat] improving UI design of team page #417 

- views/dashboard.ejs
Enhanced the UI of the dashboard
Fixes #460 (Done according to what you said, removed profile pic component)
plz check this, @swarooppatilx
> Update dashboard.ejs (UI Enhancement)

- app.js
- eslint.config.mjs
- package-lock.json
- package.json
- webpack.config.js
FEAT: Enhancing Developer Experience #119 
Fixes #119 
changes done:
- rate limiting
- helmet for security 
- cors for security
- webpack configured 
- eslint configured
>  FEAT: Enhancing Developer Experience #119 

- views/partials/head.ejs
- views/partials/navbar.ejs
[BUG] Dark mode UI #344 
Fixes #344 
>  [BUG] Dark mode UI #344 
